### ISSUE TITLE
php7在安装了opcache扩展下运行的问题

### ISSUE THREAD

**Issue by RootYQ** [hprose/hprose-pecl#15]
env：php7 + opcache + fpm
location：`hprose_writer.h`  function `_hprose_writer_write_array`

```
    HashTable *ht = Z_ARRVAL_P(val); // 这个val多进程共享
    int32_t i = zend_hash_num_elements(ht);
    if (refer) {
        hprose_writer_refer_set(refer, val);
    }
    hprose_bytes_io_putc(stream, HPROSE_TAG_LIST);
    if (i) {
        hprose_bytes_io_write_int(stream, i);
    }
    hprose_bytes_io_putc(stream, HPROSE_TAG_OPENBRACE);
    if (i) {
        zend_hash_internal_pointer_reset(ht);
        for (; i > 0; --i) {
#if PHP_MAJOR_VERSION < 7
            zval **e;
            zend_hash_get_current_data(ht, (void **)&e);
            _hprose_writer_serialize(_this, refer, stream, *e TSRMLS_CC);
#else
            zval *e = zend_hash_get_current_data(ht);
            _hprose_writer_serialize(_this, refer, stream, e TSRMLS_CC);
#endif
            zend_hash_move_forward(ht);
        }
    }
```
zval没有做分离，fpm下两个进程并发执行，会造成数组循环的数据缺失问题

**Comment by andot** [comment]
变量应该写时分离，但这里是只读操作，不知道为啥也要做分离。另外，不同进程之间会共享变量吗？这个我真不知道，我以为只有多线程下才会有共享变量的情况，多进程下，变量应该是每个进程下独立的吧。

不过这里的数组遍历方式，PHP 7 版本的写法确实应该改进，PHP7 对数组变量提供了更高效的 ZEND_HASH_FOREACH_KEY_VAL 宏方式。下个专门针对 PHP7 编写的版本会使用这种方式来遍历数组，不知道会不会解决你说的这个问题。

**Comment by RootYQ** [comment]
在安装了opcahe扩展下会共享文件编译后变量（可能说法不准确），开启两个进程用gdb进行调试，很容易观察，就是改变一个进程中的那个zval，另外一个也受到了影响（具体实现没有继续深追，可以很容易复现），数组循环时，改变了数组的内部指针，是有写操作的

**Comment by RootYQ** [comment]
另外对比mbstring里面的数组循环实现，在循环之前时加了`SEPARATE_ZVAL_NOREF `，然后分离出来一个zval进行循环的

**Comment by andot** [comment]
嗯，如果是这样的话，确实是个问题。下次专门写 PHP 7 版本的时候，我会注意一下这个问题的， 非常感谢~

**Comment by andot** [comment]
最近也有人发现有这个问题，后来发现是 PHP 核心本身的问题，PHP 7 后来专门针对这个做过修正了。使用 PHP 的每个发型版的最新版本，都可以避免遇到这个 bug。
