### ISSUE TITLE
php7.3 版本中pecl install hprose 报错

### ISSUE THREAD

**Issue by hongbin-hsu** [hprose/hprose-pecl#16]
Makefile:196: recipe for target 'hprose_common.lo' failed
make: *** [hprose_common.lo] Error 1
ERROR: `make' failed

使用github上面的源码安装则没有这个问题

**Comment by andot** [comment]
github 上的很早之前更新了，但是没有提交到 pecl 上。

**Comment by andot** [comment]
好了，已经提交了新版本，现在不仅支持 PHP 7.3，连 PHP 7.4 也支持了。
